Repository mwvgroup/Pitt-Google-Broker, pull requests merged in 2023-10, with the labels that each got.

#205 Switch ELAsTiCC consumer to an unauthenticated connection to the ZTF broker
  broker/consumer/admin.properties
  broker/consumer/ps-connector.properties
  broker/consumer/psconnect-worker.properties
  broker/consumer/vm_startup.sh
  setup/create_vms.sh
  setup/setup_broker.sh
Labels: Maintenance, Pipeline: Conductor, ELAsTiCC

#207 Fix bugs in vm_startup.sh
  broker/consumer/vm_startup.sh
Labels: Bug, ELAsTiCC

#213 Fixes bug in consumer VM startup script
  broker/consumer/vm_startup.sh
Labels: Bug, Pipeline: Conductor, ELAsTiCC
